apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
images:
- name: social-eng-app
  newName: ghcr.io/xrumdik/social-eng-app
  newTag: 58b06c22555548b9e91702e58732b53bf3d90d99
