apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
images:
- name: social-eng-app
  newName: ghcr.io/xrumdik/social-eng-app
  newTag: 8df3d380f460b5eaffdb7e789e8f1a0d2b013732
